#!/usr/bin/env node
// Everything that shows the hero outside the game is generated from the hero
// inside it. The sprite map lives once, in index.html, as HERO_PIX/HERO_PAL;
// this reads it and writes the app icons and the tile on the collection page, so
// the sprite and the artwork cannot drift apart.
//
//   node drol/tools/render-art.js          write the icons and patch the tiles
//   node drol/tools/render-art.js --check  fail if anything on disk is stale (CI)
"use strict";
const fs=require("node:fs"),path=require("node:path"),zlib=require("node:zlib");
const ROOT=path.join(__dirname,"..",".."), HERE=path.join(__dirname,"..");
const PAGE=path.join(HERE,"index.html");
const TILES=[path.join(ROOT,"index.html"),path.join(ROOT,"404.html")];
const START="<!-- drol-art: generated by drol/tools/render-art.js -->";
const END="<!-- /drol-art -->";

/* ---- the one picture of the hero, read back out of the game ---- */
function readSprite(){
 const src=fs.readFileSync(PAGE,"utf8");
 const pix=src.match(/const HERO_PIX=\[([\s\S]*?)\];/);
 const pal=src.match(/const HERO_PAL=\{([\s\S]*?)\};/);
 if(!pix||!pal)throw new Error("index.html no longer defines HERO_PIX/HERO_PAL");
 const rows=(pix[1].match(/"[^"]*"/g)||[]).map(s=>s.slice(1,-1));
 const colours={};
 for(const m of pal[1].matchAll(/([A-Za-z])\s*:\s*"(#[0-9a-fA-F]{6})"/g))colours[m[1]]=m[2];
 if(!rows.length||rows.some(r=>r.length!==rows[0].length))
   throw new Error("the sprite is not a rectangle");
 return {rows,colours,w:rows[0].length,h:rows.length};
}
// The runs of one colour in a row, which both outputs draw as single rectangles.
function* runs(sprite){
 for(let r=0;r<sprite.h;r++){
  const row=sprite.rows[r];
  let i=0;
  while(i<sprite.w){
   const ch=row[i];
   if(ch==="."||!sprite.colours[ch]){i++;continue;}
   let j=i;while(j<sprite.w&&row[j]===ch)j++;
   yield {x:i,y:r,w:j-i,colour:sprite.colours[ch]};
   i=j;
  }
 }
}

/* ---- the icon: the hero over the maze, at three sizes ---- */
let CRC=null;
function crc32(b){
 if(!CRC){CRC=[];for(let n=0;n<256;n++){let c=n;
  for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;CRC[n]=c>>>0;}}
 let c=0xffffffff;for(const x of b)c=CRC[(c^x)&255]^(c>>>8);return (c^0xffffffff)>>>0;
}
function iconPNG(sprite,size){
 const W=size,H=size,buf=Buffer.alloc(W*H*3);
 const hex=h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
 const rect=(x,y,w,h,col)=>{const c=hex(col);
  for(let j=Math.max(0,Math.round(y));j<Math.min(H,Math.round(y+h));j++)
   for(let i=Math.max(0,Math.round(x));i<Math.min(W,Math.round(x+w));i++){
    const o=(j*W+i)*3;buf[o]=c[0];buf[o+1]=c[1];buf[o+2]=c[2];}};
 rect(0,0,W,H,"#000000");                                // black, as the machine had it
 for(let f=0;f<4;f++){                                   // four floors, each with a hole
  const y=H*(.15+f*.23);
  rect(0,y,W,H*.055,"#3a34c8");
  rect(0,y,W,H*.038,"#6a62e8");
  rect(0,y,W,H*.014,"#ffffff");                          // the white edge you land on
  rect(W*(.06+f*.24),y,W*.15,H*.06,"#000000");
 }
 // The hero, centred, at whatever scale fits him into two thirds of the icon.
 const u=Math.floor(H*.62/sprite.h), ox=Math.round((W-sprite.w*u)/2), oy=Math.round(H*.21);
 rect(ox+1*u,oy+12*u,3*u,7*u,"#d838c8");                 // the jetpack, burning
 rect(ox+1*u,oy+12*u,3*u,5.5*u,"#ff8ae8");
 rect(ox+1.6*u,oy+12*u,1.6*u,4*u,"#ffffff");
 for(const r of runs(sprite))rect(ox+r.x*u,oy+r.y*u,r.w*u,u,r.colour);
 rect(ox+(sprite.w+1)*u,oy+8*u,4*u,2*u,"#ffe14a");       // a ball already on its way
 const raw=Buffer.alloc((W*3+1)*H);
 for(let y=0;y<H;y++){raw[y*(W*3+1)]=0;buf.copy(raw,y*(W*3+1)+1,y*W*3,(y+1)*W*3);}
 const chunk=(type,data)=>{
  const len=Buffer.alloc(4);len.writeUInt32BE(data.length);
  const td=Buffer.concat([Buffer.from(type),data]);
  const crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(td)>>>0);
  return Buffer.concat([len,td,crc]);};
 const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(W,0);ihdr.writeUInt32BE(H,4);
 ihdr[8]=8;ihdr[9]=2;ihdr[10]=0;ihdr[11]=0;ihdr[12]=0;
 return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),
  chunk("IHDR",ihdr),chunk("IDAT",zlib.deflateSync(raw,{level:9})),chunk("IEND",Buffer.alloc(0))]);
}

/* ---- the tile on the collection page: the same hero, as inline SVG ---- */
function tileSVG(sprite){
 // Sized so the hero and the flame under him both fit inside the tile.
 const u=+(46/sprite.h).toFixed(3), ox=+((64-sprite.w*u)/2).toFixed(2), oy=3;
 const out=[START,'        <svg viewBox="0 0 64 64">'];
 for(let f=0;f<4;f++){                                   // the four floors behind him
  const y=3+f*17;
  out.push(`          <rect x="0" y="${y}" width="64" height="3" fill="#6a62e8"/>`+
           `<rect x="0" y="${y}" width="64" height="1" fill="#ffffff"/>`);
  out.push(`          <rect x="${6+f*15}" y="${y}" width="10" height="3" fill="#000000"/>`);
 }
 out.push(`          <rect x="${(ox+u).toFixed(2)}" y="${(oy+12*u).toFixed(2)}" `+
          `width="${(3*u).toFixed(2)}" height="${(7*u).toFixed(2)}" fill="#d838c8"/>`);
 out.push(`          <rect x="${(ox+u).toFixed(2)}" y="${(oy+12*u).toFixed(2)}" `+
          `width="${(3*u).toFixed(2)}" height="${(5*u).toFixed(2)}" fill="#ff8ae8"/>`);
 for(const r of runs(sprite))
  out.push(`          <rect x="${(ox+r.x*u).toFixed(2)}" y="${(oy+r.y*u).toFixed(2)}" `+
           `width="${(r.w*u).toFixed(2)}" height="${u.toFixed(2)}" fill="${r.colour}"/>`);
 out.push('        </svg>',"      "+END);
 return out.join("\n");
}
function patchTile(file,svg){
 const src=fs.readFileSync(file,"utf8");
 const a=src.indexOf(START), b=src.indexOf(END);
 if(a<0||b<0)throw new Error(file+" has no drol-art markers");
 return src.slice(0,a)+svg.trimStart()+src.slice(b+END.length);
}

/* ---- write, or check that what is written is current ---- */
function main(argv){
 const check=argv.includes("--check");
 const sprite=readSprite();
 const jobs=[];
 for(const size of [180,192,512])
  jobs.push({file:path.join(HERE,`icon-${size}.png`),data:iconPNG(sprite,size)});
 const svg=tileSVG(sprite);
 for(const f of TILES)jobs.push({file:f,data:Buffer.from(patchTile(f,svg),"utf8")});
 const stale=[];
 for(const j of jobs){
  const now=fs.existsSync(j.file)?fs.readFileSync(j.file):null;
  if(now&&now.equals(j.data))continue;
  stale.push(path.relative(ROOT,j.file));
  if(!check)fs.writeFileSync(j.file,j.data);
 }
 if(check&&stale.length){
  console.error("These are not the current sprite:\n  "+stale.join("\n  ")+
   "\nRun: node drol/tools/render-art.js");
  process.exit(1);
 }
 console.log(check?"the artwork matches the sprite":
  stale.length?"rewrote "+stale.join(", "):"already current");
}
if(require.main===module)main(process.argv.slice(2));
module.exports={readSprite,runs,tileSVG,iconPNG};
