/* ============ content ============
 * An original recreation of the 1985 game's structure, not a port and not a
 * copy: eleven callers over one day, in the documented order, each a tree of
 * three exchanges with one visitor line and four replies at every node. Every
 * word here is newly written; no dialogue, artwork or music of the original is
 * reproduced.
 *
 * A node is either a round - {npc, replies:[4]} - or a terminal in `ends`.
 * A reply carries exactly one of:
 *   next    another round node, one exchange deeper (three at most)
 *   end     a terminal in this encounter's `ends`
 *   action  "draw"      he goes for it now
 *           "ambush"    he was never going to talk
 *           "delayed"   he walks, then turns and fires
 *           "surrender" hands up, arrest available
 *           "depart"    he leaves, and that is that
 * Drawing your own gun is always available and is not a menu line.
 *
 * A terminal emits flags the day counts: tip_train, tip_stage, tip_bank, date,
 * arrest, surrender, depart, offended, doctor_civil, doctor_insulted.
 */
const LIMITS={NPC:150,REPLY:92,ROUNDS:3,REPLIES:4};
const FLAGS=["tip_train","tip_stage","tip_bank","date","arrest","surrender",
  "depart","offended","doctor_civil","doctor_insulted","doctor_sober"];

/* The three jobs the day's tips are about. A sheriff who was told is standing
 * in the right place when it happens; a sheriff who was not reads about it. */
const JOBS={
 stage:{id:"stage", name:"The Stage Road", place:"STAGE ROAD", theme:"th_job",
   armed:true, arrive:["wagon"],
   brief:"The Thursday coach comes down the grade with the mine's money aboard, and two men step out of the rocks above the ford.",
   missed:"They took it at the ford while you were up the street. The driver is alive. Nobody else saw a thing worth telling."},
 train:{id:"train", name:"The Westbound", place:"THE CUT", theme:"th_job",
   armed:true, arrive:["wagon","crowd"],
   brief:"The westbound comes into the cut at a walking pace, and a man drops off the payroll car's step with his coat open.",
   missed:"The payroll car was opened at the cut and the westbound came in two hours late with nothing in it."},
 bank:{id:"bank", name:"The Bank", place:"BANK", theme:"th_job",
   armed:true, arrive:["crowd"],
   brief:"The back wall of the bank has a door in it that was not there yesterday, and a man in the alley turns round with his hand already moving.",
   missed:"They went through the back wall while you were at the other end of town, and the flour sack went with them."}
};

const CAST=[
 /* 1 ---------------------------------------------------------------- */
 {id:"stranger", name:"A Dude", place:"STREET", theme:"th_stranger",
  armed:true, arrive:["wagon","crowd"],
  rounds:{
   opening:{npc:"You'd be the new sheriff. Folks said you were younger than the last one. They didn't say much else.",
    replies:[
     {text:"\"Newer, anyway. What brings you to Gold Gulch?\"", next:"cordial"},
     {text:"\"They talk. You listen. What have you heard?\"", next:"business"},
     {text:"\"You've been looking up this street a while, mister.\"", next:"wary"},
     {text:"\"State your business or move along.\"", next:"prickly"}]},
   cordial:{npc:"Passing through. I came up on the westbound and I'd as soon not go back down on it.",
    replies:[
     {text:"\"Trouble on the line?\"", next:"train"},
     {text:"\"Room at the hotel, if you're staying.\"", end:"peaceful"},
     {text:"\"What's wrong with the westbound?\"", next:"train"},
     {text:"\"Then buy a horse and stop loitering.\"", end:"offended"}]},
   business:{npc:"I heard a sheriff here lasted eleven days. I heard some other things I'd want a reason to repeat.",
    replies:[
     {text:"\"The reason is the badge. Say it plain.\"", next:"train"},
     {text:"\"I'll take it kindly, and remember who told me.\"", next:"train"},
     {text:"\"Then keep them. I've enough to do.\"", end:"peaceful"},
     {text:"\"Repeat them now or in a cell.\"", end:"offended"}]},
   wary:{npc:"A man can look at a street. There's no law against standing still that I know of.",
    replies:[
     {text:"\"None at all. Stand somewhere I can see you.\"", end:"peaceful"},
     {text:"\"There's none. There's a law about what you're not saying.\"", next:"train"},
     {text:"\"Empty your coat pockets for me.\"", end:"offended"},
     {text:"\"Move.\"", end:"offended"}]},
   prickly:{npc:"You've a hard way with a stranger who's done nothing. That's how the last one started, I'd guess.",
    replies:[
     {text:"\"You're right. Start again — what did you hear?\"", next:"train"},
     {text:"\"The last one is why I'm careful.\"", end:"peaceful"},
     {text:"\"Done nothing yet. I'm early, that's all.\"", action:"delayed"},
     {text:"\"Then we'll see how you finish.\"", action:"draw"}]},
   train:{npc:"…There's men meaning to take the westbound where it slows at the cut. Payroll car. That's all I know and it's more than I should say.",
    replies:[
     {text:"\"Much obliged. Nobody hears it from me.\"", end:"tip"},
     {text:"\"Names.\"", end:"tip_hard"},
     {text:"\"Why tell me at all?\"", end:"tip"},
     {text:"\"If you're in it, say so now.\"", action:"delayed"}]}},
  ends:{
   tip:{text:"He tells it once, quietly, and is gone up the street before you have thanked him twice.",
        flags:["tip_train","depart"], authority:1},
   tip_hard:{text:"He gives you the cut, the hour and no names at all, and makes it clear that is the whole of it.",
        flags:["tip_train"], authority:0},
   peaceful:{text:"He touches his hat and goes on up the boardwalk, and the street closes behind him.",
        flags:["depart"], authority:0},
   offended:{text:"He looks at you the way a man looks at weather, and walks away without another word.",
        flags:["depart","offended"], authority:-1}}},

 /* 2 ---------------------------------------------------------------- */
 {id:"rose", name:"Miss Rose", place:"SALOON", theme:"th_rose",
  armed:false, arrive:["piano","bottle"],
  rounds:{
   opening:{npc:"Well. The badge came in for a drink at last. Sit where I can see you, Sheriff — it's the only view worth having.",
    replies:[
     {text:"\"Coffee, if the pot's honest.\"", next:"easy"},
     {text:"\"Who's been drinking here that shouldn't be?\"", next:"askers"},
     {text:"\"You see everyone who comes through that door.\"", next:"askers"},
     {text:"\"I'm working, Miss Rose.\"", next:"cool"}]},
   easy:{npc:"Honest as anything in this town. Sit long enough and the room will tell you things it wouldn't tell a stranger.",
    replies:[
     {text:"\"Then I'll sit. What's the room saying?\"", next:"stage"},
     {text:"\"You could tell me quicker.\"", next:"stage"},
     {text:"\"I'd rather hear what you think.\"", next:"warm"},
     {text:"\"I haven't the afternoon.\"", end:"ordinary"}]},
   askers:{npc:"Two men, three nights, one table. They asked what day the coach runs heavy. I told them I pour whiskey, not timetables.",
    replies:[
     {text:"\"Did they take that for an answer?\"", next:"stage"},
     {text:"\"You told them right. What else?\"", next:"stage"},
     {text:"\"Describe them.\"", next:"stage"},
     {text:"\"And you waited until now to mention it?\"", end:"ordinary"}]},
   cool:{npc:"Everybody's working. I've been working since five and I'll be working when you're asleep with your boots on.",
    replies:[
     {text:"\"Fair. Start again — sit with me a minute.\"", next:"warm"},
     {text:"\"Then work, and tell me what you've seen.\"", next:"stage"},
     {text:"\"I'll come back when there's less noise.\"", end:"ordinary"},
     {text:"\"Mind your tone with the law.\"", end:"cold"}]},
   warm:{npc:"You're better company than the badge suggested. There's a supper at the hotel Saturday, and nobody has asked me to it.",
    replies:[
     {text:"\"Then nobody has any sense. Saturday.\"", end:"date"},
     {text:"\"Saturday, if the town lets me.\"", end:"date"},
     {text:"\"Ask me again when the streets are quiet.\"", end:"ordinary"},
     {text:"\"I don't keep company in this town.\"", end:"cold"}]},
   stage:{npc:"Thursday's coach carries the mine's money. They knew that before they asked. Whoever told them drinks here too.",
    replies:[
     {text:"\"Thursday. I'm obliged to you.\"", end:"tip"},
     {text:"\"Point him out when he comes in.\"", end:"tip"},
     {text:"\"Anything else about Thursday?\"", end:"tip"},
     {text:"\"Keep your voice down and keep pouring.\"", end:"ordinary"}]}},
  ends:{
   tip:{text:"She wipes the bar where it is already clean, and says Thursday once more, quietly, in case you missed it.",
        flags:["tip_stage"], authority:1},
   date:{text:"\"Saturday,\" she says, and goes back down the bar with the particular walk of a woman who has won something.",
        flags:["date"], authority:1},
   ordinary:{text:"She nods, unsurprised, and the saloon closes over the conversation like water.",
        flags:["depart"], authority:0},
   cold:{text:"She turns to the next man at the bar and does not turn back.",
        flags:["depart","offended"], authority:-1}}},

 /* 3 ---------------------------------------------------------------- */
 {id:"kid", name:"The Mexicali Kid", place:"STREET", theme:"th_kid",
  armed:true, arrive:["hooves","spurs"],
  rounds:{
   opening:{npc:"They're offering four hundred dollars for me two counties over, Sheriff. I came to see what you'd offer.",
    replies:[
     {text:"\"A cell, three meals, and a judge in the spring.\"", next:"terms"},
     {text:"\"Four hundred says somebody wants you badly.\"", next:"talk"},
     {text:"\"Take your hand away from your belt first.\"", next:"belt"},
     {text:"\"I'll offer what you're standing on.\"", action:"draw"}]},
   terms:{npc:"A judge. In the spring. And between now and the spring I'd be in that little room of yours with the one window.",
    replies:[
     {text:"\"It's a poor room. It's better than the alternative.\"", next:"yield"},
     {text:"\"You'd be alive in it.\"", next:"yield"},
     {text:"\"Walk in on your own and I'll say so to the judge.\"", next:"yield"},
     {text:"\"Or you can try the street. Your choice.\"", action:"draw"}]},
   talk:{npc:"Wanting and having are two horses, Sheriff. Nobody has ever had me.",
    replies:[
     {text:"\"There's a first day for everything.\"", next:"yield"},
     {text:"\"Then ride on before somebody tries.\"", next:"leave"},
     {text:"\"Four hundred buys a lot of men willing to try.\"", next:"leave"},
     {text:"\"Today's the day, Kid.\"", action:"draw"}]},
   belt:{npc:"My hand is where my hand lives. You're the one who keeps looking at it.",
    replies:[
     {text:"\"Then we'll both look somewhere else.\"", next:"leave"},
     {text:"\"Move it, slowly, and we'll talk about the spring.\"", next:"yield"},
     {text:"\"You came a long way to be careful.\"", next:"leave"},
     {text:"\"Move it or use it.\"", action:"draw"}]},
   leave:{npc:"Ride on. That's the first sensible thing said to me in this county.",
    replies:[
     {text:"\"Then take it and go.\"", action:"depart"},
     {text:"\"Go south. Don't come back through here.\"", action:"depart"},
     {text:"\"Go — but the four hundred rides with you.\"", action:"delayed"},
     {text:"\"You'll go in irons or not at all.\"", action:"draw"}]},
   yield:{npc:"…The spring, then. On your word, Sheriff, and your word had better be worth the ride.",
    replies:[
     {text:"\"It is. Hands where I can see them.\"", action:"surrender"},
     {text:"\"You have it. Walk ahead of me.\"", action:"surrender"},
     {text:"\"My word, and the judge's mercy after.\"", action:"surrender"},
     {text:"\"My word is a cell. Nothing after it.\"", action:"draw"}]}},
  ends:{}},

 /* 4 ---------------------------------------------------------------- */
 {id:"doctor", name:"The Doctor", place:"DOCTOR", theme:"th_doctor",
  armed:false, arrive:["crowd"], doctor:true, roots:["opening","opening_drunk"],
  rounds:{
   /* Which of the two he opens with is settled at dawn, not by the player. */
   opening_drunk:{npc:"Sheriff. I have had a night of it and a bottle after the night, and I am ashamed of neither. Ask me what you like, but ask it slowly.",
    replies:[
     {text:"\"Then sit down and take the coffee instead.\"", next:"coffee"},
     {text:"\"Slowly, then. What have you heard this week?\"", next:"listen"},
     {text:"\"You're the only doctor in sixty miles, Doc.\"", next:"coffee"},
     {text:"\"A drunk doctor is no doctor at all.\"", next:"sour"}]},
   coffee:{npc:"…The pot is on the stove and it is yesterday's. You would have to pour it yourself and stand over me while I drank it, and you have a street to walk.",
    replies:[
     {text:"\"The street will keep. Drink it.\"", end:"sobered"},
     {text:"\"I'll pour, and stand here till it's gone.\"", end:"sobered"},
     {text:"\"Drink it or don't. I've said my piece.\"", end:"still_drinking"},
     {text:"\"Sleep it off. Try to be useful by dark.\"", end:"insulted"}]},
   opening:{npc:"Sheriff. I dug a ball out of a freighter's shoulder at four this morning and I'd like to know whether I'll be doing it again tonight.",
    replies:[
     {text:"\"Not if the day goes the way I mean it to.\"", next:"civil"},
     {text:"\"You hear things in that surgery. What have you heard?\"", next:"listen"},
     {text:"\"That depends on who walks up this street.\"", next:"civil"},
     {text:"\"Doctors bury opinions with the patients, Doc.\"", next:"sour"}]},
   civil:{npc:"Then we understand each other. I've no objection to the law. I object to sewing up what it leaves behind.",
    replies:[
     {text:"\"So do I. I'd rather arrest than shoot.\"", next:"listen"},
     {text:"\"Keep your kit ready anyway.\"", next:"listen"},
     {text:"\"You'd rather I let men walk?\"", end:"grudging"},
     {text:"\"Stick to your trade and I'll keep to mine.\"", end:"insulted"}]},
   listen:{npc:"A man under laudanum says what he wouldn't say sober. One of them said a good deal about the bank's back wall.",
    replies:[
     {text:"\"Go on. I'll keep his name out of it.\"", end:"bank"},
     {text:"\"When was this?\"", end:"bank"},
     {text:"\"That's worth knowing. Thank you.\"", end:"bank"},
     {text:"\"You should have come to me at four this morning.\"", end:"grudging"}]},
   sour:{npc:"My trade is what's left of men like you when the day is over. I'd remember that, if I were the one wearing the star.",
    replies:[
     {text:"\"You're right, and I'm sorry for it. Say your piece.\"", next:"listen"},
     {text:"\"I'll remember. I'd still take a warning if you have one.\"", next:"listen"},
     {text:"\"Remember it yourself. I've a street to walk.\"", end:"insulted"},
     {text:"\"Keep your sermon for the ones who don't make it.\"", end:"insulted"}]}},
  ends:{
   bank:{text:"He tells you the hour and the wall, and then goes back inside to boil his instruments, which is his way of ending a conversation.",
         flags:["tip_bank","doctor_civil"], authority:1},
   grudging:{text:"\"At four this morning I had my hands inside a man,\" he says, and shuts the door. He will still come if you are shot, but he will not hurry.",
         flags:["tip_bank"], authority:0},
   insulted:{text:"\"Then don't send for me,\" he says, loud enough for the street. Several people hear him say it.",
         flags:["doctor_insulted","offended"], authority:-1},
   sobered:{text:"He drinks it scalding, twice, and by the second cup his hands have stopped and he is looking at you like a man again.",
         flags:["doctor_sober","doctor_civil"], authority:1},
   still_drinking:{text:"He puts the cork back in the bottle and sets it where he can reach it, which is the whole of his answer.",
         flags:[], authority:0}}},

 /* 5 ---------------------------------------------------------------- */
 {id:"shotgun", name:"Dude with a New Gun", place:"STREET", theme:"th_shotgun",
  armed:true, arrive:["spurs","crowd"],
  rounds:{
   opening:{npc:"Look at it, Sheriff. Forty dollars in Kansas City and it come out of the crate oiled. You'll not see another like it this side of the river.",
    replies:[
     {text:"\"That's a handsome piece of work. Mind the hammer.\"", next:"admire"},
     {text:"\"Forty dollars is a deal of money for a man to be carrying.\"", next:"money"},
     {text:"\"Put it back in the leather while we talk.\"", next:"order"},
     {text:"\"A new gun and an old habit. Which one brought you here?\"", next:"probe"}]},
   admire:{npc:"You know guns, then. Most men see a gun and see trouble coming. I see forty dollars of Kansas City work and a thing that fits my hand.",
    replies:[
     {text:"\"I see both. Keep it pointed at the dirt.\"", next:"intent"},
     {text:"\"Where does a man your age come by forty dollars?\"", next:"intent"},
     {text:"\"Show me how it sits in the holster.\"", end:"holstered"},
     {text:"\"Sell it before somebody makes you use it.\"", next:"proud"}]},
   money:{npc:"I had a piece of work up in Ellsworth. Honest, most of it. The part that wasn't is not written down anywhere a man could go and read it.",
    replies:[
     {text:"\"Then we'll leave it unwritten. Mind how you go.\"", end:"holstered"},
     {text:"\"Tell me the part that wasn't.\"", next:"intent"},
     {text:"\"Nothing stays unwritten. Hand me the gun.\"", next:"proud"},
     {text:"\"Ellsworth. I'll wire them tonight.\"", action:"delayed"}]},
   order:{npc:"It's in my hand because it's mine. You'd be the first man in this town to tell me where to keep my own property, and I've been here a week.",
    replies:[
     {text:"\"Then hold it and listen. Nobody's taking it.\"", next:"intent"},
     {text:"\"I'll be the first and the last. Holster it.\"", next:"proud"},
     {text:"\"Your property. My street.\"", next:"proud"},
     {text:"\"Holster it or lose the hand.\"", action:"draw"}]},
   probe:{npc:"Habits. Every man's got habits. Mine is shooting bottles off the corral rail of an evening, and there is no law in this territory about bottles.",
    replies:[
     {text:"\"There isn't. Shoot bottles and we'll stay friends.\"", end:"holstered"},
     {text:"\"Bottles don't cost forty dollars. What does?\"", next:"intent"},
     {text:"\"There's a law about what comes after bottles.\"", next:"intent"},
     {text:"\"Shoot one now and I'll show you the law.\"", action:"ambush"}]},
   proud:{npc:"You've a way of speaking to a man that gets a town a new sheriff every spring. I'll put it away when I am done looking at it and not before.",
    replies:[
     {text:"\"Look at it, then. I'll wait.\"", end:"holstered"},
     {text:"\"Last spring's sheriff. What became of him?\"", end:"warned"},
     {text:"\"You're done. Set it on the rail.\"", action:"surrender"},
     {text:"\"You'll put it away now or in the dust.\"", action:"draw"}]},
   intent:{npc:"…All right. A man at the livery says the bank's takings go out Friday in a flour sack. I only wanted to know if a sheriff would be watching.",
    replies:[
     {text:"\"Now I am. Set the gun down and walk to the jail.\"", action:"surrender"},
     {text:"\"Who is the man at the livery?\"", end:"tip"},
     {text:"\"You've told me. Go home and stay there.\"", end:"warned"},
     {text:"\"You wanted to know. Now you do.\"", action:"draw"}]}},
  ends:{
   holstered:{text:"He turns it over once more, the way a man does with a thing he has paid too much for, and puts it away.",
        flags:["depart"], authority:1},
   tip:{text:"He gives the name at the livery and the day with it, and looks like a man who has set down something heavy.",
        flags:["tip_bank","depart"], authority:1},
   warned:{text:"He goes, and not toward the livery, and the new gun stays in the leather the whole length of the street.",
        flags:["depart"], authority:0}}},

 /* 6 ---------------------------------------------------------------- */
 {id:"willie", name:"Little Willy", place:"STREET", theme:"th_willie",
  armed:false, arrive:["crowd"],
  rounds:{
   opening:{npc:"Sheriff! I ain't supposed to be up this end of town and I ain't supposed to tell you neither, so you can't say it was me that said it.",
    replies:[
     {text:"\"Nobody hears it from me, Willy. Sit on the rail.\"", next:"kind"},
     {text:"\"What's it worth, then? I've a nickel says a nickel.\"", next:"deal"},
     {text:"\"Say it quick, then. I've a street to walk.\"", next:"brisk"},
     {text:"\"If you've done something, say so now.\"", next:"stern"}]},
   kind:{npc:"You're the only one calls me Willy instead of boy. Ma says a sheriff's got no time for boys. You've got some, though, ain't you.",
    replies:[
     {text:"\"As much as this takes. Go on.\"", next:"secret"},
     {text:"\"I've time for anybody who saw something.\"", next:"secret"},
     {text:"\"Not much of it. What did you see?\"", next:"clam"},
     {text:"\"Then don't waste it. Out with it.\"", next:"clam"}]},
   deal:{npc:"A nickel! Mister Hanley gives a nickel for sweeping out the whole store. A secret's got to be worth more than sweeping a store.",
    replies:[
     {text:"\"It is. Tell it and we'll settle after.\"", next:"secret"},
     {text:"\"Two bits if it's true and if it's mine first.\"", next:"secret"},
     {text:"\"You don't sell what you know to the law, Willy.\"", next:"clam"},
     {text:"\"I don't buy from boys. Go home.\"", end:"sent"}]},
   brisk:{npc:"I can say it fast. I only want to know first whether I'm saying it to the sheriff or to the man who drinks coffee with my ma of a Sunday.",
    replies:[
     {text:"\"To the sheriff. Your ma hears nothing.\"", next:"secret"},
     {text:"\"To both, and neither of them tells.\"", next:"secret"},
     {text:"\"To the sheriff. That's the only one here today.\"", next:"clam"},
     {text:"\"You're saying it to a man in a hurry.\"", next:"clam"}]},
   stern:{npc:"I ain't done nothing! I only saw a thing. Seeing ain't doing. Ma says seeing ain't doing and she says it about you as well.",
    replies:[
     {text:"\"Your ma's right and I'm sorry. What did you see?\"", next:"secret"},
     {text:"\"Seeing isn't doing. Telling isn't either. Go on.\"", next:"secret"},
     {text:"\"Then seeing is what I want. Quickly.\"", next:"clam"},
     {text:"\"Boys who see things get shot at. Home.\"", end:"scared"}]},
   secret:{npc:"Two men been out back of the bank with a rope, measuring along the wall. They gave me a nickel not to say and I already spent it on liquorice.",
    replies:[
     {text:"\"Then it's paid for already. You did right, Willy.\"", end:"tip"},
     {text:"\"Measuring with a rope. What day was that?\"", end:"tip"},
     {text:"\"You keep the liquorice. I'll keep the rope.\"", end:"tip"},
     {text:"\"You took their money? Get home.\"", end:"scared"}]},
   clam:{npc:"…No. I promised. A promise is a promise even when it's a bad one, Ma says. Ask me something else and I'll answer that.",
    replies:[
     {text:"\"Then keep it. That's a fair thing to do.\"", end:"kept"},
     {text:"\"Come and find me when it stops being a promise.\"", end:"kept"},
     {text:"\"Promises don't hold against the law, son.\"", end:"kept"},
     {text:"\"You'll say it now or say it in the jail.\"", end:"scared"}]}},
  ends:{
   tip:{text:"He tells it in one breath and then again slower, in case the first time was too fast, and runs for the corner before you can thank him.",
        flags:["tip_bank","depart"], authority:1},
   kept:{text:"He goes off up the boardwalk with it still in him, walking slowly, hoping the whole way to be called back.",
        flags:["depart"], authority:0},
   sent:{text:"He shrugs the way a boy shrugs when he has decided not to mind, and goes back down toward the store.",
        flags:["depart"], authority:0},
   scared:{text:"He runs. Two women outside the milliner's watch him go, and then look at you for rather a long time.",
        flags:["depart","offended"], authority:-1}}},

 /* 7 ---------------------------------------------------------------- */
 {id:"april", name:"Miss April", place:"SCHOOL", theme:"th_april",
  armed:false, arrive:["crowd"],
  rounds:{
   opening:{npc:"Sheriff. The children have been at the window all morning saying the new sheriff would be shot before dinner. I told them that was not arithmetic.",
    replies:[
     {text:"\"Nor is it manners. What are they learning instead?\"", next:"warm"},
     {text:"\"They may be better at it than arithmetic. What have they seen?\"", next:"seen"},
     {text:"\"Keep them at the window. They see more than I do.\"", next:"seen"},
     {text:"\"Then teach them to mind their own business.\"", next:"cool"}]},
   warm:{npc:"Long division, and not gracefully. It is a quiet post. A woman may go a month here without being asked a single question worth answering.",
    replies:[
     {text:"\"Then ask me one. I'll try to be worth it.\"", next:"supper"},
     {text:"\"I'll ask you one a day if it helps.\"", next:"supper"},
     {text:"\"Ask the window, then. What does it show?\"", next:"window"},
     {text:"\"Quiet is what I'm paid for, ma'am.\"", end:"ordinary"}]},
   seen:{npc:"The schoolhouse looks down the grade to where the westbound slows. The children count the cars. Lately they have been counting men instead.",
    replies:[
     {text:"\"Men. Where, and how many?\"", next:"window"},
     {text:"\"Children count better than deputies. Go on.\"", next:"window"},
     {text:"\"Keep them counting. I'll come back at four.\"", next:"supper"},
     {text:"\"Children imagine. Don't bring me imagining.\"", end:"alienated"}]},
   cool:{npc:"I have taught in three towns, Sheriff, and been told to mind my business in every one of them. It has never once been good advice.",
    replies:[
     {text:"\"It wasn't this time either. I'm sorry — go on.\"", next:"window"},
     {text:"\"Then give me yours instead of minding it.\"", next:"window"},
     {text:"\"In this town it is the only advice I have.\"", end:"ordinary"},
     {text:"\"Three towns, and not one of them kept you.\"", end:"alienated"}]},
   supper:{npc:"There is a supper at the hotel on Saturday. I have been asked twice already by men I do not care for, and I am running out of ways to say no.",
    replies:[
     {text:"\"Then say yes to one you haven't met properly.\"", end:"date"},
     {text:"\"Say no again and let me ask you on Sunday.\"", end:"date"},
     {text:"\"I'd take you, if the town lets me. It may not.\"", end:"date"},
     {text:"\"I'd stay clear of hotel suppers this week.\"", end:"ordinary"}]},
   window:{npc:"Four men, three mornings, at the cut where the grade slows the westbound. They were not counting cars. One of them had a rifle rolled in a blanket.",
    replies:[
     {text:"\"At the cut. That's a day's work you've done.\"", end:"tip"},
     {text:"\"Keep the children inside tomorrow morning.\"", end:"tip"},
     {text:"\"A rifle in a blanket. Anything else?\"", end:"tip"},
     {text:"\"Four men and a blanket is not evidence.\"", end:"alienated"}]}},
  ends:{
   tip:{text:"She writes the hour on a slate in a clear hand, turns it round for you to read, and wipes it off again with her sleeve.",
        flags:["tip_train"], authority:1},
   date:{text:"\"Saturday,\" she says, and goes back in to the long division with something in her step that was not there before.",
        flags:["date"], authority:1},
   ordinary:{text:"She closes the schoolhouse door quietly, which somehow says a great deal more than slamming it would have.",
        flags:["depart"], authority:0},
   alienated:{text:"\"Good day, Sheriff,\" she says, in the voice she keeps for boys who have not done the work.",
        flags:["depart","offended"], authority:-1}}},

 /* 8 ---------------------------------------------------------------- */
 {id:"gambler", name:"The Gambler", place:"SALOON", theme:"th_gambler",
  armed:true, arrive:["piano","crowd"],
  rounds:{
   opening:{npc:"Sheriff. Sit in. Four hands teaches a man more about a town than a year of asking questions, and I have learned that nobody here can bluff.",
    replies:[
     {text:"\"I don't play. I'll watch a hand.\"", next:"watch"},
     {text:"\"Show me the deck you've been learning with.\"", next:"deck"},
     {text:"\"Stand up and turn out your sleeves.\"", next:"sleeves"},
     {text:"\"You've cleaned out two freighters this week. Out.\"", next:"hard"}]},
   watch:{npc:"Watch, then. It is an honest game with honest men and I have had honest luck for eleven nights running, which is a thing that happens.",
    replies:[
     {text:"\"Eleven nights is a deal of luck for one man.\"", next:"caught"},
     {text:"\"Deal one hand face up and I'll believe you.\"", next:"caught"},
     {text:"\"Enjoy the twelfth somewhere else.\"", next:"leave"},
     {text:"\"Luck like that gets a man buried, not rich.\"", next:"leave"}]},
   deck:{npc:"It is the house's deck. Ask the man behind the bar. I have not carried my own cards since Natchez, and Natchez was a misunderstanding.",
    replies:[
     {text:"\"Natchez. Tell me about the misunderstanding.\"", next:"caught"},
     {text:"\"Then you'll not mind me cutting it.\"", next:"caught"},
     {text:"\"That's a long way to come for a misunderstanding.\"", next:"leave"},
     {text:"\"Hand it here, house deck or not.\"", next:"caught"}]},
   sleeves:{npc:"…I will stand. I will not turn out anything in front of six men who owe me money. You can see the difficulty in it, Sheriff.",
    replies:[
     {text:"\"Then step outside and turn them out there.\"", next:"caught"},
     {text:"\"I can. Outside, or here in front of all of them.\"", next:"caught"},
     {text:"\"I see six men who'd like their money back.\"", next:"leave"},
     {text:"\"Turn them out or I'll turn them out for you.\"", action:"draw"}]},
   hard:{npc:"Two freighters who could not count. That is not cheating, that is arithmetic, and there is no statute against arithmetic in this territory.",
    replies:[
     {text:"\"There's one against what's up your left cuff.\"", next:"caught"},
     {text:"\"Give them back their wages and we're square.\"", next:"leave"},
     {text:"\"There's a statute about me. Move.\"", next:"leave"},
     {text:"\"Then we'll settle it without one.\"", action:"draw"}]},
   caught:{npc:"…A holdout clip. Well. Eleven good nights. What is it precisely that you would like me to do about it now, Sheriff?",
    replies:[
     {text:"\"Set it on the table and walk to the jail.\"", action:"surrender"},
     {text:"\"Pay the freighters back, then the jail.\"", action:"surrender"},
     {text:"\"Leave the money and leave the territory.\"", action:"depart"},
     {text:"\"Nothing. I want the whole room to see it.\"", action:"delayed"}]},
   leave:{npc:"Then I shall finish this hand and be on the noon coach. You will not see me again and you will not miss me by Thursday.",
    replies:[
     {text:"\"Finish it standing up and go.\"", action:"depart"},
     {text:"\"Leave the hand. Take the coach.\"", action:"depart"},
     {text:"\"The coach — and the freighters' wages on the bar.\"", end:"repaid"},
     {text:"\"You'll go when I say and not before.\"", action:"delayed"}]}},
  ends:{
   repaid:{text:"He counts it out without hurrying, touches his hat to the room, and is on the boardwalk before the deck has been shuffled.",
        flags:["depart"], authority:1}}},

 /* 9 ---------------------------------------------------------------- */
 {id:"deputy", name:"The Deputy", place:"JAIL", theme:"th_deputy",
  armed:true, arrive:["hooves"],
  rounds:{
   opening:{npc:"Sheriff! There's men at the bank. There was. I run the whole way from the corner and now I ain't certain what I saw, but I'm certain I saw it.",
    replies:[
     {text:"\"Slow down. Tell it in the order it happened.\"", next:"order"},
     {text:"\"How many, and were they mounted?\"", next:"count"},
     {text:"\"You're certain or you're not. Which is it?\"", next:"press"},
     {text:"\"You've been certain twice this week already.\"", next:"sting"}]},
   order:{npc:"I come round by the assay office and there was two horses stood at the bank's back wall with nobody holding them. Horses don't stand like that.",
    replies:[
     {text:"\"No, they don't. Go on — what else?\"", next:"confirm"},
     {text:"\"Two horses. Anything in the alley?\"", next:"confirm"},
     {text:"\"Horses stand where they're tied, Deputy.\"", next:"doubt"},
     {text:"\"You ran all this way to tell me about horses.\"", next:"doubt"}]},
   count:{npc:"Two. Maybe three. Mounted — no, stood, and one up on the boardwalk in a coat that was wrong for the weather we're having.",
    replies:[
     {text:"\"A coat wrong for the weather is worth the run.\"", next:"confirm"},
     {text:"\"Three men and a heavy coat. Where's your gun?\"", next:"confirm"},
     {text:"\"Two, maybe three. That is not a report.\"", next:"doubt"},
     {text:"\"Come back when the number stops moving.\"", next:"doubt"}]},
   press:{npc:"…Certain. I am certain. I'd not have run if I wasn't and I'd not be stood here letting you look at me like that either.",
    replies:[
     {text:"\"Then I'm certain too. Get the shotgun.\"", next:"confirm"},
     {text:"\"Good man. Tell me the rest as we walk.\"", next:"confirm"},
     {text:"\"You've been certain about a deal of things.\"", next:"doubt"},
     {text:"\"Looking at you is all I've done. Try being right.\"", next:"doubt"}]},
   sting:{npc:"Twice, and both times you went and both times it was nothing, and you have not let me forget either of them. This one is not nothing.",
    replies:[
     {text:"\"Then this is the one that counts. Show me.\"", next:"confirm"},
     {text:"\"You're right. I've been hard on you. Go on.\"", next:"confirm"},
     {text:"\"Third time pays for all, they say. Prove it.\"", next:"doubt"},
     {text:"\"Three for three, then. Sit down, Deputy.\"", next:"doubt"}]},
   confirm:{npc:"Back wall, two horses, and the coat. If you want me at the front I'll take the front, and if you want me nowhere I'll take that too.",
    replies:[
     {text:"\"Take the front. I'll come round the back.\"", end:"ready"},
     {text:"\"You've done well. Get the shotgun and follow.\"", end:"ready"},
     {text:"\"Nowhere. Stay here and mind the jail.\"", end:"alone"},
     {text:"\"You'll take the back, and you'll go first.\"", end:"pushed"}]},
   doubt:{npc:"…All right. All right, Sheriff. Maybe it was horses. I'll go back by the corner and look again, and I'll not run this time.",
    replies:[
     {text:"\"Look again. Come straight to me either way.\"", end:"ready"},
     {text:"\"No. We'll both look, and we'll look now.\"", end:"ready"},
     {text:"\"Do that. And Deputy — walk, don't run.\"", end:"dismissed"},
     {text:"\"Don't trouble. Mind the jail and let me work.\"", end:"dismissed"}]}},
  ends:{
   ready:{text:"He is out of the door before you are, and for once in the day you are following a man who knows where he is going.",
        flags:["tip_bank"], authority:1},
   alone:{text:"He takes the keys and the chair by the stove, and does not look up when you go out.",
        flags:["tip_bank"], authority:0},
   pushed:{text:"He goes where he is sent, white about the mouth, and the men on the boardwalk watch him being sent.",
        flags:["tip_bank","offended"], authority:-1},
   dismissed:{text:"He hangs his hat back on the nail and says nothing at all, which from him is a great deal.",
        flags:["depart"], authority:-1}}},

 /* 10 --------------------------------------------------------------- */
 {id:"belle", name:"Belle", place:"CORRAL", theme:"th_belle",
  armed:true, arrive:["hooves"],
  rounds:{
   opening:{npc:"You'll be wanting the two steers with the Bar-K burn on them. They're in my corral and I'll not pretend they walked in there by themselves.",
    replies:[
     {text:"\"You'll not pretend. That's a start. Why are they there?\"", next:"why"},
     {text:"\"Then they can walk out again, and you with them.\"", next:"out"},
     {text:"\"Whose iron did the second burn, Belle?\"", next:"iron"},
     {text:"\"Two steers is a rope in this territory.\"", next:"rope"}]},
   why:{npc:"Because Kinch at the Bar-K runs his stock over my water and calls it open range. I took two. He has taken my water for three years running.",
    replies:[
     {text:"\"Three years is a grievance, not a defence.\"", next:"square"},
     {text:"\"Then we'll take it to the judge, water and all.\"", next:"square"},
     {text:"\"Drive them back tonight and I'll speak for you.\"", next:"turn"},
     {text:"\"He'll get the judge and you'll get the rope.\"", next:"square"}]},
   out:{npc:"They can. I'll walk them back myself at first light and Kinch can count them twice. It is what I meant to do before you came up the hill.",
    replies:[
     {text:"\"Then I'll ride out and watch him count.\"", next:"turn"},
     {text:"\"First light. I'll be here at first light.\"", next:"turn"},
     {text:"\"You'll walk them back now, and I'll follow.\"", next:"square"},
     {text:"\"You meant nothing of the kind.\"", next:"square"}]},
   iron:{npc:"Mine. I burned it over his and I made a poor job of it, which you can see from where you are stood, and I did not much care that you could.",
    replies:[
     {text:"\"A poor job and an honest answer. Sit down.\"", next:"turn"},
     {text:"\"You cared, or you'd not have said it that way.\"", next:"turn"},
     {text:"\"Then come down to the jail and say it again.\"", next:"square"},
     {text:"\"Careless and a thief. Hands where I see them.\"", next:"square"}]},
   rope:{npc:"It is. It's a rope for a man as well. You'll notice nobody has hung Kinch over the water, and nobody in this county is going to.",
    replies:[
     {text:"\"Nobody's hanging anybody today. Talk to me.\"", next:"turn"},
     {text:"\"Then let me be the first to ask him about it.\"", next:"turn"},
     {text:"\"Kinch isn't stood in front of me. You are.\"", next:"square"},
     {text:"\"Keep talking and we'll see about the rope.\"", action:"draw"}]},
   square:{npc:"…So it's the jail. Say it straight out, Sheriff, and let me fetch my coat. I would rather that than be talked round to it by degrees.",
    replies:[
     {text:"\"It's the jail, and I'll speak to the judge for you.\"", action:"surrender"},
     {text:"\"Fetch it. The water goes in the record too.\"", action:"surrender"},
     {text:"\"No jail. Drive them back and we never spoke.\"", action:"depart"},
     {text:"\"Fetch your coat, and be quick about it.\"", action:"delayed"}]},
   turn:{npc:"You are the first man off that road in three years to say a thing to me that was not about cattle. There is a dance at the grange on Saturday.",
    replies:[
     {text:"\"Then I'll come up the road again Saturday.\"", end:"date"},
     {text:"\"Saturday, and I'll not mention cattle once.\"", end:"date"},
     {text:"\"Drive them back first. Then ask me again.\"", end:"steers"},
     {text:"\"I came about the steers, Belle. Only the steers.\"", end:"steers"}]}},
  ends:{
   date:{text:"She whistles the dog off the gate and walks you as far as the road, which is further than she has walked anybody in three years.",
        flags:["date"], authority:1},
   steers:{text:"She drives them back at first light, Kinch counts them twice, and she does not look at you once the whole way down.",
        flags:["depart"], authority:1}}},

 /* 11 --------------------------------------------------------------- */
 {id:"lastgun", name:"The Last Gunfighter", place:"STREET", theme:"th_lastgun",
  armed:true, arrive:["spurs"], forcedDuel:true,
  standoff:"He has been across the street since noon and has not said one word. The boardwalk has emptied from both ends.",
  rounds:{}, ends:{}}
];
const written=e=>!!(e.rounds&&e.rounds.opening);

/* ============ the pixel grid ============
 * A 320x200 logical screen, presented in 4:3 the way a C64 was. The sheriff
 * stands in the left foreground, seen from behind and drawn in the largest
 * blocks on the screen; the visitor stands deeper in the street, smaller and
 * finer. The hitboxes are read off the visitor's own grid, so what the
 * crosshair is over is what the bullet finds, for every one of them.
 */
const SCENE={w:320,h:200};
const CELL=2;                            // the block the street furniture is built on

/* ============ the eleven figures ============
 * Each caller is his own 24x20 grid, painted two scene-pixels to a cell with a
 * one-pixel dark contour round the silhouette. No two share a grid: the hats,
 * the coat length, the skirt, the boy's height and the gambler's tails are what
 * tell them apart at this size, not the colours.
 *   . nothing  H hat   R hair  F face  E eye     C coat   K coat shadow
 *   W linen    L legs and skirts       A skin    G gunmetal
 *   B dark (belts, boots, bags)        S star    P prop (bag, slate, cards, rope)
 * `raise` is the sparse overlay for the hand coming up, and `box` gives the
 * cells the bullet has to find: torso, weapon at rest, weapon raised.        */
/* A caller is 24 pixels across and 28 cells tall drawn two pixels to the row:
 * 24 by 56 on the screen, the proportions a man has at this distance rather
 * than the squat block a square cell gave. */
const SPR={w:24,h:28}, FIGCW=1, FIGCH=2, FIGCELL=FIGCW;
const DEFAULT_BOX={lethal:[7,6,16,13], weapon:[2,12,5,15], raised:[1,6,5,9]};
const FIGURES={
  stranger:{rows:[
  ".........HHHHHH.........",
  "........HHHHHHHH........",
  "......HHHHHHHHHHHH......",
  ".......FFFFFFFFFF.......",
  "........FFEFFEFF........",
  ".........FFFFFF.........",
  "......CCCCWWWWCCCC......",
  ".....CCCCCWWWWCCCCC.....",
  "....CCCCCCWWWWCCCCCC....",
  "....CCCCCCCWWCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  "....CCCCBBBBBBBBCCCC....",
  "...ACCCCCCCCCCCCCCCCA...",
  "...AGCCCCCCCCCCCCCCAA...",
  "...GGCCCCCCCCCCCCCCC....",
  "...GGCCCCCCCCCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  ".....CCCCCC..CCCCCC.....",
  ".....CCCCCC..CCCCCC.....",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  ".....BBBB......BBBB.....",
  ".....BBBB......BBBB....."],
  raise:{6:"...AGCCCCWWWWCCCC......",
         7:"...GGCCCCWWWWCCCCC.....",
         12:"....CCCCCCCCCCCCCCCCA...",
         13:"....CCCCCCCCCCCCCCCAA...",
         14:"....CCCCCCCCCCCCCCCC....",
         15:"....CCCCCCCCCCCCCCCC...."},
  box:{lethal:[7,6,16,13], weapon:[2,12,5,17], raised:[1,6,5,9]}},
  rose:{rows:[
  "........RRRRRR..........",
  ".......RRRRRRRR.........",
  "......RRRRRRRRRR........",
  ".......RFFFFFFR.........",
  "........FFEFFEF.........",
  ".........FFFFF..........",
  "........AAAAAAA.........",
  ".......AAWWWWAAA........",
  "......AWWWWWWWWA........",
  "......WWWWWWWWWW........",
  ".....WWWWWWWWWWWW.......",
  ".....KKKKKKKKKKKK.......",
  "....LLLLLLLLLLLLLL......",
  "...LLLLLLLLLLLLLLLL.....",
  "..LLLLLLLLLLLLLLLLLL....",
  "..LLLLLLLLLLLLLLLLLL....",
  "..LLLLLLLLLLLLLLLLLL....",
  "..LLLLLLLLLLLLLLLLLL....",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  ".LLLLLLLLLLLLLLLLLLLL...",
  "...BBBB........BBBB.....",
  "...BBBB........BBBB....."],
  box:{lethal:[6,6,15,12], weapon:[2,12,5,17], raised:[1,6,5,9]}},
  kid:{rows:[
  ".........HHHHHH.........",
  "........HHHHHHHH........",
  "...HHHHHHHHHHHHHHHHH....",
  "..HHHHHHHHHHHHHHHHHHH...",
  ".......FFFFFFFF.........",
  "......FFFEFFEFFF........",
  ".......FFFFFFFF.........",
  "......CCCCCCCCCC........",
  ".....CCGCCCCGCCCC.......",
  "....CCCGCCCCGCCCCC......",
  "....CCCCGCCGCCCCCC......",
  "....CCCCCGGCCCCCCC......",
  "...ACCCBBBBBBBBCCCA.....",
  "...AGCCCCCCCCCCCCAA.....",
  "...GGCCCCCCCCCCCCC......",
  "...GGCCCCCCCCCCCCC......",
  "....LLLLLL..LLLLLL......",
  "....LLLLLL..LLLLLL......",
  "....LLLLLL..LLLLLL......",
  "....LLLLLL..LLLLLL......",
  "....LLLLLL..LLLLLL......",
  "....LLLLLL..LLLLLL......",
  "....LLLLLL..LLLLLL......",
  "...BBBBBB....BBBBBB.....",
  "...BBBBBB....BBBBBB.....",
  "...BBBBBB....BBBBBB.....",
  "...BBBBBB....BBBBBB.....",
  "...BBBBBB....BBBBBB....."],
  raise:{6:"...AGCFFFFFFFF.........",
         7:"...GGCCCCCCCCCC........",
         12:"....CCCBBBBBBBBCCCA.....",
         13:"....CCCCCCCCCCCCCAA.....",
         14:"....CCCCCCCCCCCCCC......",
         15:"....CCCCCCCCCCCCCC......"},
  box:{lethal:[7,6,16,13], weapon:[2,12,5,17], raised:[1,6,5,9]}},
  doctor:{rows:[
  "........BBBBBB..........",
  ".......BBBBBBBB.........",
  "......BBBBBBBBBB........",
  ".......FFFFFFFF.........",
  "......FEFFFFFEF.........",
  ".......FFFFFFF..........",
  "......CCWWWWWWCC........",
  ".....CCCWWWWWWCCC.......",
  ".....CCCWKKKKWCCC.......",
  ".....CCCWWWWWWCCC.......",
  ".....CCCCWWWWCCCC.......",
  ".....CCCBBBBBBCCC.......",
  "....ACCCCCCCCCCCCA......",
  "....ACCCCCCCCCCCAA......",
  "...PPPPPCCCCCCCCC.......",
  "...PPPPPCCCCCCCCC.......",
  "...PPPPPLLLLLLLL........",
  "...PPPPPLLLLLLLL........",
  "...PPPPPLLL..LLL........",
  "...PPPPPLLL..LLL........",
  "........LLL..LLL........",
  "........LLL..LLL........",
  "........LLL..LLL........",
  "........LLL..LLL........",
  "........LLL..LLL........",
  "........LLL..LLL........",
  ".......BBBB..BBBB.......",
  ".......BBBB..BBBB......."],
  box:{lethal:[6,6,16,13], weapon:[3,14,7,22], raised:[3,14,7,22]}},
  shotgun:{rows:[
  ".........HHHHHH.........",
  "........HHHHHHHH........",
  ".......HHHHHHHHHH.......",
  "........FFFFFFFF........",
  ".......FFFEFFEFF........",
  "........FFFFFFF.........",
  "......WWWWWWWWWWW.......",
  ".....WWWWWWWWWWWWW......",
  "....WWWWWWWWWWWWWWW.....",
  "..GGGGGGGGGGGGGGWWW.....",
  "..GGGGGGGGGGGGGGGGG.....",
  "...AAWWWWWWWWWAAWWW.....",
  "....WWWWBBBBBWWWWW......",
  "....LLLLLLLLLLLLL.......",
  "....LLLLLLLLLLLLL.......",
  "....LLLLLLLLLLLLL.......",
  "....LLLLLL..LLLLL.......",
  "....LLLLLL..LLLLL.......",
  "....LLLLLL..LLLLL.......",
  "....LLLLLL..LLLLL.......",
  "....LLLLLL..LLLLL.......",
  "....LLLLLL..LLLLL.......",
  "....LLLLLL..LLLLL.......",
  "...BBBBBB....BBBBB......",
  "...BBBBBB....BBBBB......",
  "...BBBBBB....BBBBB......",
  "...BBBBBB....BBBBB......",
  "...BBBBBB....BBBBB......"],
  raise:{7:"..GGGGGGGGGGGGGWWW......",
         8:"..GGGGGGGGGGGGGGGGG.....",
         9:"...AAWWWWWWWWWAAWWW.....",
         10:"....WWWWWWWWWWWWWWW.....",
         11:"....WWWWWWWWWWWWWWW....."},
  box:{lethal:[8,6,16,8], weapon:[2,9,7,11], raised:[2,7,7,9]}},
  willie:{rows:[
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  "........................",
  ".........HHHHH..........",
  "........HHHHHHH.........",
  ".........FFFFF..........",
  "........FFEFFEF.........",
  ".........FFFFF..........",
  ".......WWWWWWWWW........",
  "......WWWWWWWWWWW.......",
  "......AWWWWWWWWWA.......",
  "......AWWWWWWWWWA.......",
  "......AWWWWWWWWWA.......",
  "......AWWWWWWWWWA.......",
  ".......LLLLLLLLL........",
  ".......LLLLLLLLL........",
  ".......LLLL.LLLL........",
  ".......LLLL.LLLL........",
  ".......LLLL.LLLL........",
  ".......LLLL.LLLL........",
  ".......LLLL.LLLL........",
  ".......LLLL.LLLL........",
  "......AAAA...AAAA.......",
  "......AAAA...AAAA......."],
  box:{lethal:[8,12,15,22], weapon:[5,14,7,17], raised:[5,14,7,17]}},
  april:{rows:[
  "........RRRRRR..........",
  ".......RRRRRRRR.........",
  ".......RRRRRRRRR........",
  "........FFFFFF..........",
  ".......FFEFFEFF.........",
  "........FFFFFF..........",
  ".......WWWWWWWW.........",
  "......CCWWWWWWCC........",
  "......CCCCCCCCCC........",
  "......CCCCCCCCCC........",
  "......CCCCCCCCCC........",
  "......CCCCCCCCCC........",
  "...PPPCCCCCCCCCCA.......",
  "...PPPCCCCCCCCCAA.......",
  "...PPPLLLLLLLLLL........",
  "...PPPLLLLLLLLLL........",
  "......LLLLLLLLLL........",
  "......LLLLLLLLLL........",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  ".....LLLLLLLLLLLL.......",
  "......BBB....BBB........",
  "......BBB....BBB........"],
  box:{lethal:[6,6,15,13], weapon:[3,12,5,15], raised:[3,12,5,15]}},
  gambler:{rows:[
  ".......HHHHHHHH.........",
  ".......HHHHHHHH.........",
  ".......HHHHHHHH.........",
  ".....HHHHHHHHHHHH.......",
  "........FFFFFF..........",
  ".......FFEFFEFF.........",
  "........FFFFFF..........",
  "......CCCWWWWCCC........",
  ".....CCCCWWWWCCCC.......",
  ".....CCCCWPPWCCCC.......",
  ".....CCCCWWWWCCCC.......",
  ".....CCCBBBBBBCCC.......",
  "..AGCCCCCCCCCCCPPPPP....",
  "..GGCCCCCCCCCCCCPPP.....",
  "...CCCCCCCCCCCCCCP......",
  "...CCCCCCCCCCCCCCP......",
  "....CCCCCCCCCCCCC.......",
  "....CCCCCCCCCCCCC.......",
  "....CCCCC..CCCCCC.......",
  "....CCCCC..CCCCCC.......",
  ".....LLL....LLLL........",
  ".....LLL....LLLL........",
  ".....LLL....LLLL........",
  ".....LLL....LLLL........",
  ".....LLL....LLLL........",
  ".....LLL....LLLL........",
  "....BBBB....BBBBB.......",
  "....BBBB....BBBBB......."],
  raise:{7:"..AGCCCCWWWWCCC.........",
         8:"..GGCCCCWWWWCCCC........",
         12:"....CCCCCCCCCCCPPPPP....",
         13:"....CCCCCCCCCCCCPPP.....",
         14:"....CCCCCCCCCCCCCP......",
         15:"....CCCCCCCCCCCCCP......"},
  box:{lethal:[7,6,16,11], weapon:[2,12,5,15], raised:[2,7,5,9]}},
  deputy:{rows:[
  ".........HHHHH..........",
  "........HHHHHHH.........",
  ".......HHHHHHHHH........",
  "......HHHHHHHHHHH.......",
  "........FFFFFF..........",
  ".......FFEFFEFF.........",
  "........FFFFFF..........",
  "......CCCWWWWCCC........",
  ".....CCCCWWWWCCCC.......",
  ".....CCSCWWWWCCCC.......",
  ".....CCCCWWWWCCCC.......",
  ".....CCCBBBBBBCCC.......",
  "...ACCCCCCCCCCCCA.......",
  "...AGCCCCCCCCCCAA.......",
  "...GGCCCCCCCCCCC........",
  "...GGCCCCCCCCCCC........",
  "...GGLLLLL.LLLLL........",
  "...GGLLLLL.LLLLL........",
  "...GGLLLLL.LLLLL........",
  "...GGLLLLL.LLLLL........",
  "...GGLLLLL.LLLLL........",
  "...GGLLLLL.LLLLL........",
  "...GGLLLLL.LLLLL........",
  "..BBBBBBB...BBBBB.......",
  "..BBBBBBB...BBBBB.......",
  "..BBBBBBB...BBBBB.......",
  "..BBBBBBB...BBBBB.......",
  "..BBBBBBB...BBBBB......."],
  raise:{6:"...AGCCFFFFFF...........",
         7:"...GGCCCWWWWCCC.........",
         8:"...GGCCCCWWWWCCCC.......",
         12:"....CCCCCCCCCCCA.......",
         13:"....CCCCCCCCCCAA.......",
         16:".....LLLLL.LLLLL........",
         17:".....LLLLL.LLLLL........",
         18:".....LLLLL.LLLLL........",
         19:".....LLLLL.LLLLL........",
         20:".....LLLLL.LLLLL........",
         21:".....LLLLL.LLLLL........",
         22:".....LLLLL.LLLLL........"},
  box:{lethal:[7,6,16,13], weapon:[2,13,5,22], raised:[2,6,5,9]}},
  belle:{rows:[
  "......HHHHHHHHHH........",
  ".....HHHHHHHHHHHH.......",
  "........RRRRRR..........",
  ".......RFFFFFFR.........",
  "........FFEFFEF.........",
  ".........FFFFF..........",
  "......WWWWWWWWWW........",
  ".....WWWWWWWWWWWW.......",
  ".....WWWWWWWWWWWW.......",
  ".....WWWWWWWWWWWW.......",
  "....PPWWWWWWWWWWW.......",
  "...PPPPBBBBBBBWWW.......",
  "...PPPPCCCCCCCCCA.......",
  "...AGCCCCCCCCCCAA.......",
  "...GGCCCCCCCCCCC........",
  "...GGCCCCCCCCCCC........",
  "....LLLLLL.LLLLL........",
  "....LLLLLL.LLLLL........",
  "....LLLLLL.LLLLL........",
  "....LLLLLL.LLLLL........",
  "....LLLLLL.LLLLL........",
  "....LLLLLL.LLLLL........",
  "....LLLLLL.LLLLL........",
  "...BBBBBB...BBBBB.......",
  "...BBBBBB...BBBBB.......",
  "...BBBBBB...BBBBB.......",
  "...BBBBBB...BBBBB.......",
  "...BBBBBB...BBBBB......."],
  raise:{6:"...AGCWWWWWWWWWW........",
         7:"...GGCWWWWWWWWWWW.......",
         13:"....CCCCCCCCCCCAA.......",
         14:"....CCCCCCCCCCCC........",
         15:"....CCCCCCCCCCCC........"},
  box:{lethal:[6,6,16,12], weapon:[2,12,5,17], raised:[1,6,5,8]}},
  lastgun:{rows:[
  "........HHHHHH..........",
  ".......HHHHHHHH.........",
  ".....HHHHHHHHHHHH.......",
  "....HHHHHHHHHHHHHH......",
  "........FFFFFF..........",
  ".......FFEFFEFF.........",
  "........FFFFFF..........",
  "......KKKKKKKKKK........",
  ".....KKKKKKKKKKKK.......",
  "....KKKKKKKKKKKKKK......",
  "....KKKKKKKKKKKKKK......",
  "....KKKKKKKKKKKKKK......",
  "..AKKKKKKKKKKKKKKA......",
  "..AGKKKKKKKKKKKKAA......",
  "..GGKKKKKKKKKKKKKK......",
  "..GGKKKKKKKKKKKKKK......",
  "...KKKKKKKKKKKKKK.......",
  "...KKKKKKKKKKKKKK.......",
  "...KKKKKK..KKKKKKK......",
  "...KKKKKK..KKKKKKK......",
  "....LLLL....LLLLL.......",
  "....LLLL....LLLLL.......",
  "....LLLL....LLLLL.......",
  "....LLLL....LLLLL.......",
  "....LLLL....LLLLL.......",
  "....LLLL....LLLLL.......",
  "...BBBB......BBBBB......",
  "...BBBB......BBBBB......"],
  raise:{6:"..AGKKKKKKKKKKKK........",
         7:"..GGKKKKKKKKKKKKKK......",
         12:"...KKKKKKKKKKKKKKA......",
         13:"...KKKKKKKKKKKKKAA......",
         14:"...KKKKKKKKKKKKKKK......",
         15:"...KKKKKKKKKKKKKKK......"},
  box:{lethal:[6,6,17,13], weapon:[1,12,4,17], raised:[1,6,4,8]}},
  robber:{rows:[
  ".........HHHHHH.........",
  "........HHHHHHHH........",
  "......HHHHHHHHHHHH......",
  ".......KKKKKKKKKK.......",
  "........KKEKKEKK........",
  ".........KKKKKK.........",
  "......CCCCCCCCCCCC......",
  ".....CCCCCCCCCCCCCC.....",
  "....CCCCCCCCCCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  "....CCCCBBBBBBBBCCCC....",
  "..AGCCCCCCCCCCCCCCCCA...",
  "..GGCCCCCCCCCCCCCCCAA...",
  "..GGCCCCCCCCCCCCCCCC....",
  "..GGCCCCCCCCCCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  "....CCCCCCCCCCCCCCCC....",
  ".....CCCCCC..CCCCCC.....",
  ".....CCCCCC..CCCCCC.....",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  "......LLLL....LLLL......",
  ".....BBBB......BBBB.....",
  ".....BBBB......BBBB....."],
  raise:{6:"..AGCCCCCCCCCCCCCC......",
         7:"..GGCCCCCCCCCCCCCCCC....",
         12:"....CCCCCCCCCCCCCCCCA...",
         13:"....CCCCCCCCCCCCCCCAA..."},
  box:{lethal:[7,6,16,13], weapon:[1,12,4,17], raised:[1,6,4,8]}}
};
/* Hands up: an overlay any figure can wear, so surrender reads at a glance. */
const SURRENDER={0:"..AAA..............AAA..",1:"..AAA..............AAA..",
  2:"..AAA..HHHHHH......AAA..",3:"..AAA..FFFFFF......AAA..",
  4:"..AAA..FFEFFE......AAA..",5:"...AA...FFFFF.......AA.."};

const FIG={cx:190, ground:150};          // the caller, in the middle of the street
const SPRX=FIG.cx-(SPR.w/2)*FIGCW;
const SPRY=FIG.ground-SPR.h*FIGCH;
const cellsBox=(c0,r0,c1,r1)=>({x:SPRX+c0*FIGCW,y:SPRY+r0*FIGCH,
  w:(c1-c0+1)*FIGCW,h:(r1-r0+1)*FIGCH});
const figureOf=e=>(e&&FIGURES[e.figure||e.id])||FIGURES.robber;
function boxesFor(e){
  const b=figureOf(e).box||DEFAULT_BOX;
  return {lethal:cellsBox(b.lethal[0],b.lethal[1],b.lethal[2],b.lethal[3]),
          weapon:cellsBox(b.weapon[0],b.weapon[1],b.weapon[2],b.weapon[3]),
          weaponRaised:cellsBox(b.raised[0],b.raised[1],b.raised[2],b.raised[3])};
}
const HITBOX=boxesFor(null);             // the default, for anything asking without a caller
