#!/usr/bin/env node
// Everything that shows the chopper outside the game is generated from the
// chopper inside it. The sprite lives once, in index.html, as CHOP3/CHOP_PAL;
// this reads it and writes the app icons and the tile on the collection page,
// so the sprite and the artwork cannot drift apart.
//
//   node choplifter/tools/render-art.js          write the icons and patch the tiles
//   node choplifter/tools/render-art.js --check  fail if anything on disk is stale (CI)
"use strict";
const fs=require("node:fs"),path=require("node:path"),zlib=require("node:zlib");
const ROOT=path.join(__dirname,"..",".."), HERE=path.join(__dirname,"..");
const PAGE=path.join(HERE,"index.html");
const TILES=[path.join(ROOT,"index.html"),path.join(ROOT,"404.html")];
const START="<!-- choplifter-art: generated by choplifter/tools/render-art.js -->";
const END="<!-- /choplifter-art -->";

/* ---- the one picture of the chopper, read back out of the game ---- */
function readSprite(){
 const src=fs.readFileSync(PAGE,"utf8");
 // The icon shows her in profile, which is the shape everybody remembers.
 const pix=src.match(/const CHOP3=\[([\s\S]*?)\];/);
 const pal=src.match(/const CHOP_PAL=\{([\s\S]*?)\};/);
 if(!pix||!pal)throw new Error("index.html no longer defines CHOP3/CHOP_PAL");
 const rows=(pix[1].match(/"[^"]*"/g)||[]).map(s=>s.slice(1,-1));
 const colours={};
 for(const m of pal[1].matchAll(/([A-Za-z])\s*:\s*"(#[0-9a-fA-F]{6})"/g))colours[m[1]]=m[2];
 if(!rows.length||rows.some(r=>r.length!==rows[0].length))
   throw new Error("the sprite is not a rectangle");
 // The rotor is drawn, not stored, so the artwork has to be told where the hub
 // is rather than guessing. Both halves are read out of the page: the radius
 // from the constant the game shares between its four frames, the hub from the
 // last of them, which is the profile this icon shows.
 const rot=src.match(/const ROTOR=\[([\s\S]*?)\];/);
 const rad=src.match(/const ROTOR_R=(\d+)/);
 const hubs=rot?[...rot[1].matchAll(/hx:(\d+),hy:(\d+)/g)]:[];
 const last=hubs.length?hubs[hubs.length-1]:null;
 if(!rad||!last)
   throw new Error("index.html no longer says where the rotor is (ROTOR_R/ROTOR)");
 // And two of the people she came for, because a helicopter on its own is a
 // helicopter and a helicopter over two men waving is Choplifter.
 const wave=src.match(/const HOST_WAVE=\[([\s\S]*?)\];/);
 const hpal=src.match(/const HOST_PAL=\{([\s\S]*?)\};/);
 if(!wave||!hpal)throw new Error("index.html no longer defines HOST_WAVE/HOST_PAL");
 const wrows=(wave[1].match(/"[^"]*"/g)||[]).map(x=>x.slice(1,-1)).slice(0,9);
 const wcol={};
 for(const m of hpal[1].matchAll(/([A-Za-z])\s*:\s*"(#[0-9a-fA-F]{6})"/g))wcol[m[1]]=m[2];
 return {rows,colours,w:rows[0].length,h:rows.length,
   hub:{x:+last[1],y:+last[2],r:+rad[1]},
   man:{rows:wrows,colours:wcol,w:wrows[0].length,h:wrows.length}};
}
// The runs of one colour in a row, which both outputs draw as single rectangles.
function* runs(sprite){
 for(let r=0;r<sprite.h;r++){
  const row=sprite.rows[r];
  let i=0;
  while(i<sprite.w){
   const ch=row[i];
   if(ch==="."||!sprite.colours[ch]){i++;continue;}
   let j=i;while(j<sprite.w&&row[j]===ch)j++;
   yield {x:i,y:r,w:j-i,colour:sprite.colours[ch]};
   i=j;
  }
 }
}

/* ---- the icon: the chopper over the line, at three sizes ---- */
let CRC=null;
function crc32(b){
 if(!CRC){CRC=[];for(let n=0;n<256;n++){let c=n;
  for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;CRC[n]=c>>>0;}}
 let c=0xffffffff;for(const x of b)c=CRC[(c^x)&255]^(c>>>8);return (c^0xffffffff)>>>0;
}
// Android crops a maskable icon to a circle or a squircle and may take a fifth
// off every side, so the maskable one is the same picture drawn into the middle
// sixty per cent of the square. Drawn full-bleed, as it was, the mask takes the
// rotor tips and both of the people off it.
function iconPNG(sprite,size,maskable){
 const W=size,H=size,buf=Buffer.alloc(W*H*3);
 const hex=h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
 const rect=(x,y,w,h,col)=>{const c=hex(col);
  for(let j=Math.max(0,Math.round(y));j<Math.min(H,Math.round(y+h));j++)
   for(let i=Math.max(0,Math.round(x));i<Math.min(W,Math.round(x+w));i++){
    const o=(j*W+i)*3;buf[o]=c[0];buf[o+1]=c[1];buf[o+2]=c[2];}};
 // The dawn she flies into, banded rather than graded so it survives being
 // shrunk to a home-screen icon.
 rect(0,0,W,H,"#0b1436");
 rect(0,H*.40,W,H*.22,"#2a2a5c");
 rect(0,H*.62,W,H*.10,"#7c4a6a");
 const GY=Math.round(maskable?H*.70:H*.80);
 rect(0,H*.72,W,GY-H*.72,"#e0925a");
 rect(0,GY,W,H*.03,"#4f9d4a");
 rect(0,GY+H*.03,W,H,"#b9925c");
 // Her, in profile, filling most of the width. The blades run off both edges,
 // which is what a rotor does to a square picture of a helicopter.
 const u=Math.max(1,Math.floor(W*(maskable?.54:.86)/sprite.w));
 const ox=Math.round((W-sprite.w*u)/2), oy=Math.round(H*(maskable?.32:.24));
 const bar=Math.max(1,Math.round(u*.9));
 const bx=maskable?ox-u*3:0, bw=maskable?(sprite.w+6)*u:W;
 rect(bx,oy+(sprite.hub.y+.4)*u,bw,Math.max(1,u*.5),"#8fa4c8");
 rect(bx,oy+(sprite.hub.y-.5)*u,bw,bar,"#f2f7ff");
 for(const r of runs(sprite))rect(ox+r.x*u,oy+r.y*u,r.w*u,u,r.colour);
 // And two of them on the ground, waving her down.
 const m=sprite.man, mu=Math.max(1,Math.floor(u*(maskable?.75:.55)));
 const men=maskable?[Math.round(W*.30),Math.round(W*.58)]
                   :[Math.round(W*.16),Math.round(W*.68)];
 for(const mx of men)
  for(const r of runs(m))rect(mx+r.x*mu,GY-m.h*mu+r.y*mu,r.w*mu,mu,r.colour);
 const raw=Buffer.alloc((W*3+1)*H);
 for(let y=0;y<H;y++){raw[y*(W*3+1)]=0;buf.copy(raw,y*(W*3+1)+1,y*W*3,(y+1)*W*3);}
 const chunk=(type,data)=>{
  const len=Buffer.alloc(4);len.writeUInt32BE(data.length);
  const td=Buffer.concat([Buffer.from(type),data]);
  const crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(td)>>>0);
  return Buffer.concat([len,td,crc]);};
 const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(W,0);ihdr.writeUInt32BE(H,4);
 ihdr[8]=8;ihdr[9]=2;ihdr[10]=0;ihdr[11]=0;ihdr[12]=0;
 return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),
  chunk("IHDR",ihdr),chunk("IDAT",zlib.deflateSync(raw,{level:9})),chunk("IEND",Buffer.alloc(0))]);
}

/* ---- the tile on the collection page: the same chopper, as inline SVG ---- */
function tileSVG(sprite){
 const out=[START,'        <svg viewBox="0 0 64 64">'];
 const R=(x,y,w,h,c)=>out.push(`          <rect x="${(+x).toFixed(2)}" y="${(+y).toFixed(2)}" `+
   `width="${(+w).toFixed(2)}" height="${(+h).toFixed(2)}" fill="${c}"/>`);
 const u=+(60/sprite.w).toFixed(3), ox=2, oy=7;
 R(0,52,64,2,"#4f9d4a");R(0,54,64,10,"#b9925c");
 // The disc, drawn to the width of the tile: a rotor in a square picture runs
 // off both sides of it.
 R(0,oy+(sprite.hub.y+.4)*u,64,Math.max(.8,u*.5),"#8fa4c8");
 R(0,oy+(sprite.hub.y-.5)*u,64,Math.max(1.4,u*.9),"#f2f7ff");
 for(const r of runs(sprite))R(ox+r.x*u,oy+r.y*u,r.w*u,u,r.colour);
 const m=sprite.man, mu=+(u*.55).toFixed(3);
 for(const mx of [7,45])
  for(const r of runs(m))R(mx+r.x*mu,52-m.h*mu+r.y*mu,r.w*mu,mu,r.colour);
 out.push('        </svg>',"      "+END);
 return out.join("\n");
}

function patchTile(file,svg){
 const src=fs.readFileSync(file,"utf8");
 const a=src.indexOf(START), b=src.indexOf(END);
 if(a<0||b<0)throw new Error(file+" has no choplifter-art markers");
 return src.slice(0,a)+svg.trimStart()+src.slice(b+END.length);
}

/* ---- write, or check that what is written is current ---- */
function main(argv){
 const check=argv.includes("--check");
 const sprite=readSprite();
 const jobs=[];
 for(const size of [180,192,512])
  jobs.push({file:path.join(HERE,`icon-${size}.png`),data:iconPNG(sprite,size)});
 jobs.push({file:path.join(HERE,"icon-maskable-512.png"),data:iconPNG(sprite,512,true)});
 const svg=tileSVG(sprite);
 for(const f of TILES)jobs.push({file:f,data:Buffer.from(patchTile(f,svg),"utf8")});
 const stale=[];
 for(const j of jobs){
  const now=fs.existsSync(j.file)?fs.readFileSync(j.file):null;
  if(now&&now.equals(j.data))continue;
  stale.push(path.relative(ROOT,j.file));
  if(!check)fs.writeFileSync(j.file,j.data);
 }
 if(check&&stale.length){
  console.error("These are not the current sprite:\n  "+stale.join("\n  ")+
   "\nRun: node choplifter/tools/render-art.js");
  process.exit(1);
 }
 console.log(check?"the artwork matches the sprite":
  stale.length?"rewrote "+stale.join(", "):"already current");
}
if(require.main===module)main(process.argv.slice(2));
module.exports={readSprite,runs,tileSVG,iconPNG};
